[package]
name = "uwuid"
version = "0.2.0"
authors = ["Anson Cheung <git@anson-cheung.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "^0.8.2"
itertools = "^0.10.0"